services:
  postgres:
    image: postgres:16
    container_name: customer-postgres
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    ports:
      - "5432:5432"
    volumes:
      - customer_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: customer-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: customer
      RABBITMQ_DEFAULT_PASS: customer
    ports:
      - "5672:5672"
      - "15672:15672"

  wiremock:
    image: wiremock/wiremock:3.9.1
    container_name: customer-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: customer-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

volumes:
  customer_postgres_data:
